name: automoldesigner
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9.16
  - pytorch==1.13.1
  - torchvision==0.14.1
  - torchaudio==0.13.1
  - pytorch-cuda=11.6
  - pip
  - pip:
    - autogluon==0.8.2
    - rdkit==2023.3.3
    - molvs==0.1.1
    - descriptastorus==2.6.1
    - dimorphite-dl==1.3.2
    - openpyxl